{{- if .Values.keycloakClientEnabled }}
{{- $values := .Values -}}
{{- $release := .Release -}}
 {{- range $client := .Values.keycloakClients }}

apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ $release.Name }}-{{ $client.clientID }}-client
  namespace: {{ $release.Namespace }}

  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    clientId: {{ $client.clientID  }}
    secret: {{ $client.clientSecret }}
  {{- if $client.additionalClientSpec }}
{{ toYaml $client.additionalClientSpec | indent 4 }}
  {{- end }}
  {{- if $client.additionalSpec }}
{{ toYaml $client.additionalSpec | indent 2 }}
  {{- end }}

---
 {{- end }}
{{- end }}
