{{- if .Values.OAuthPatchEnabled }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: {{ .Release.Name }}-oauth-patch
  namespace: resource-locker-operator 
spec:
  serviceAccountRef: 
    name: default
  patches:
  - targetObjectRef:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      name: cluster
    patchTemplate: |
      spec:
        identityProviders:
        - mappingMethod: claim
          name: openid
          openID:
{{- if .Values.keycloakCABundleEnabled }}
            ca:
              name: {{ .Values.caBundleCM | default "ca-bundle" }}
{{- end }}
            claims:
              email:
              - email
              name:
              - name
              preferredUsername:
              - preferred_username
            clientID: {{ .Values.clientId| default "openshift" }} 
            clientSecret:
              name: {{ .Release.Name }}-oauth-secret 
            extraScopes: []
            issuer: https://{{ .Values.keycloakHostname | default "keycloak.local" }}/auth/realms/{{ .Values.openshiftOAuthRealm }}
          type: OpenID
      
    id: {{ .Release.Name }}-patch 
    patchType: application/merge-patch+json 
{{- end }}
