{{- if .Values.keycloakClientEnabled }}
{{- $values := .Values -}}
{{- $release := .Release -}}
  {{- range $client := .Values.keycloakClients }}
    {{- if $client.createOpenshiftSecret }}

apiVersion: v1
stringData:
  clientSecret: {{ $client.clientSecret  }}
kind: Secret
metadata:
  name: {{ $release.Name }}-oauth-secret
  namespace: openshift-config
type: Opaque
     {{- end }}
  {{- end }}
{{- end }}
