{{- if .Values.keycloakInstance.argocdConfig.project.createProject }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.keycloakInstance.argocdConfig.project.name }}
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

{{- end }}
