keycloakInstall: true
keycloakRouteEnabled: true
keycloakRealmEnabled: true
keycloakClientEnabled: true
keycloakCABundleEnabled: true
keycloakHostname: "keycloak.local"
openshiftOAuthRealm: "openshift"
OAuthPatchEnabled: true
caBundle:
  data:
    ca-bundle: |+
      -----BEGIN CERTIFICATE-----
      YOU CERT IS HERE
      -----END CERTIFICATE-----




keycloak:
  keycloakClusterSize: 1
  additionalSpec: {}
keycloakRealms:
  - name: openshift-oauth
    additionalRealmSpec: {}
    additionalSpec: {}
  - name: some-other-realm
    additionalRealmSpec: {}
    additionalSpec: {}


keycloakClients:
  - clientID: openshift
    clientSecret: supersecret
    createOpenshiftSecret: "true" 
    additionalClientSpec:
        protocol: openid-connect
        clientAuthenticatorType: client-secret
        redirectUris:
        - "https://console-openshift-console.apps*"
        - "https://oauth-openshift.apps*"
        publicClient: False
        serviceAccountsEnabled: True
        standardFlowEnabled: True
  - clientID: client2
    clientSecret: supersecret2
    additionalClientSpec:
      client:
        protocol: openid-connect
keycloakUsers:
  - name: admin
    spec:
      realmSelector:
        matchLabels:
          app: sso
      user:
        credentials:
        - type: password
          value: "changeme" 
        email: "admin@advatys.com"
        firstName: "FirstName"
        lastName:  "LastName" 
        username: "admin" 
        enabled: True
        emailVerified: False
        realmRoles:
        - "offline_access"
        clientRoles:
          account:
          - "manage-account"
          realm-management:
          - "manage-users"
  - name: secondadmin
    spec:
      realmSelector:
        matchLabels:
          app: sso
      user:
        credentials:
        - type: password
          value: "changemenow"
        email: "secondadmin@advatys.com"
        firstName: "FirstName"
        lastName:  "LastName"
        username: "secondadmin"
        enabled: True
        emailVerified: False
        realmRoles:
        - "offline_access"
        clientRoles:
          account:
          - "manage-account"
          realm-management:
          - "manage-users"

      
      
